//
//  UserTaskRouter.swift
//  CODIUM
//
//  Created by Malyadri on 13/12/19.
//  Copyright (c) 2019 codium. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTaskRouterInterface {
  // Navigation functions
}

class UserTaskRouter: UserTaskRouterInterface {
  weak var viewController: UserTaskViewController?
 
}
