//
//  UserTaskPresenter.swift
//  CODIUM
//
//  Created by Malyadri on 13/12/19.
//  Copyright (c) 2019 codium. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTaskPresenterInterface {
  func presentUserTaskList(response: UserTask.GetUserTaskList.Response)
  func presentSaveResponse(response: UserTask.SaveTask.Response)
  func presentDeleteTaskResponse(response: UserTask.DeleteTask.Response)
}

class UserTaskPresenter: UserTaskPresenterInterface {
  weak var viewController: UserTaskViewControllerInterface?
  
  func presentUserTaskList(response: UserTask.GetUserTaskList.Response) {
    viewController?.displayUserTaskList(viewModel: UserTask.GetUserTaskList.ViewModel(taskList: response.taskList))
  }
  
  func presentSaveResponse(response: UserTask.SaveTask.Response) {
    viewController?.displaySaveTask(viewModel: UserTask.SaveTask.ViewModel(success: response.success))
  }
  
  func presentDeleteTaskResponse(response: UserTask.DeleteTask.Response) {
    viewController?.displayDeleteTask(viewModel: UserTask.DeleteTask.ViewModel(success: response.success))
  }
  
}
