//
//  UserTaskModels.swift
//  CODIUM
//
//  Created by Malyadri on 13/12/19.
//  Copyright (c) 2019 codium. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct UserTask {
  
  // To get task list
  struct GetUserTaskList {
    struct Request {}
    
    struct Response {
      let taskList: [String]
    }
    
    struct ViewModel {
      let taskList: [String]
    }
  }
  
  struct SaveTask {
    struct Request {
      let task: String
    }
    
    struct Response {
      let success: Bool
    }
    
    struct ViewModel {
     let success: Bool
    }
  }
  
  struct DeleteTask {
    struct Request {
      let task: String
    }
    
    struct Response {
      let success: Bool
    }
    
    struct ViewModel {
      let success: Bool
    }
  }
}
