//
//  TodoListPresenter.swift
//  CODIUM
//
//  Created by Malyadri on 13/12/19.
//  Copyright (c) 2019 codium. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListPresenterInterface {
  func presentTodoList(response: Todo.GetTodoList.Response)
}

class TodoListPresenter: TodoListPresenterInterface {
  weak var viewController: TodoListViewControllerInterface!
  
  func presentTodoList(response: Todo.GetTodoList.Response) {
    let viewModel = Todo.GetTodoList.ViewModel(todoList: response.todoList)
    viewController.displayTodoList(viewModel: viewModel)
  }
 
}
