//
//  TodoListModels.swift
//  CODIUM
//
//  Created by Malyadri on 13/12/19.
//  Copyright (c) 2019 codium. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Todo {
  
  //Model to get Todo List
  struct GetTodoList {
    struct Request {}
    
    struct Response {
      let todoList: [String]
    }
    struct ViewModel {
      let todoList: [String]
    }
  }
}
